version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: aplikasi_pertamaku
    environment:
      - SUBDOMAIN=SilviDianPramana










